---
title: 'Tutorial: Week 3'
author:
 - Deparment of Statistics
 - University of New South Wales
output:
  pdf_document: default
  html_notebook: default
  word_document: default
  html_document:
    df_print: paged
---

```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```
  
### Lynx Data
  
Consider the annual number (and their logarithms) of lynx trappings in the Mackenzie River District of North-West Canada for the period 1821 to 1934. The data is available as *LYNX.txt* file on Moodle. The series appears to exhibit an approximately 10-year cycle. The autocorrelation and partial autocorrelation functions of the logged series indicate that the partial autocorrelation becomes insignificant after lag 11. A reasonably good model for the logarithms of the data—based on the Akaike Information Criterion (AIC)—is an AR(11) model with coefficients: 1.139, -0.508, 0.213, -0.270, 0.113, -0.124, 0.068, -0.040, 0.134, 0.185, -0.311. The autoregressive polynomial has all its roots, including some complex pairs, located outside the unit circle, indicating stationarity. Residual diagnostics suggest that the model provides a good fit to the data.
  

Repeat the analysis on the logged lynx data, fit an appropriate AR model, and comment on the outputs, including model selection, estimated coefficients, stationarity, and residual diagnostics.
  
  
  

### Simulating ARMA time series

This exercise introduces methods for simulation of stationary ARMA($p,q$)
time series. By completing this exercise you will have a better understanding
of how autocorrelation functions and partial autocorrelation functions are
related to parameter values in the ARMA specification. Also you will learn how
sampling variation impacts the estimated autocorrelations and partial autocorrelations.

A sample script for specifying an ARMA model, plotting the true ACF and PACF
and simulating several realisations from the model is given in the file
*ARMAsims.r*.


**Before you start**: Use the *?arima.sim* and *?arima*
help requests and read the documentation so that you understand how R
specifies the ARMA model, particularly the signs of the AR and MA coefficients.
Also check the manual entry for *?polyroot* - this function allows you
to check if the AR and MA parameters you have chosen satisfy the stationarity
and invertibility conditions. Example given in the script file. Understand this!

**Tasks**: Experiment by changing the values of the AR, the MA and noise
standard deviation parameters as well as the sample size using the code in
*ARMAsims.r* - Explore and enjoy, but make some notes about what you
are learning.

### Finding a good ARMA model

This exercise is concerned with developing an ARMA($p,q$) model for the time
series of wave heights discussed in the reference by Cowperwaite and Metcalfe
(2009). These are heights relative to still water level measured at the centre of a wave tank with waves generated by a wave-maker programmed to emulate a rough sea. Since there is no trend or seasonal the assumption of stationarity is probably reasonable.

Commands to read in the data and perform analysis required below are available in the R script file *WaveTankChapter3.r*

- Examine the data for several consecutive subsets of time (for example in 6 
blocks of 66 time points). Decide if the series appears to be at least weakly
stationary. Discuss with a classmate.

- Use the *ar.yw* command to automatically find the degree of the autoregression which minimizes AIC of model fit. Compare the fitted AR coefficients with their standard errors
and determine which are individually significant at the approximate $5\%$ level. Check the autogression for stationarity - it should be because the Yule-Walker method guarantees that.

- Examine the residuals from that choice using the ACF and PACF as well as
a qqnorm plot. Are these white noise?

- Experiment with different mixed ARMA specifications. Start with the ARMA(2,1) model provided, look at the residual ACF and PACF and try to reason your way to other choices of orders $(p,q)$. The aim is to find a more parsimonious model than the best AR model which has similar residual properties (white noise) and has smaller prediction variance.

- Conclude: What is your final model? Summarise the parameter values in a
mathematical equation with standard errors. Also state the residual variance
estimate and discuss how well the residuals conform to Gaussian white noise.

